<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>DemoTracerBotHider</AssemblyName>
    <RootNamespace>BotHiderImpl</RootNamespace>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.371">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" GeneratePathProperty="true">
      <Private>false</Private>
    </PackageReference>
    <ProjectReference Include="..\BotHiderApi\BotHiderApi.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DemoTracer.Tests" />
  </ItemGroup>

  <Target Name="CopyHarmony" AfterTargets="Build;Publish">
    <Copy SourceFiles="$(PkgLib_Harmony)\lib\net10.0\0Harmony.dll"
          DestinationFolder="$(OutDir)shared\0Harmony"
          SkipUnchangedFiles="true" />
  </Target>

</Project>
