<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>BotControllerImpl</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.371">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DemoTracer.Tests" />
    <ProjectReference Include="../BotControllerApi/BotControllerApi.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="../../../../plugins/DemoTracerApi/DemoTracerApi.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
